config/routes.rb
Rails.application.routes.draw do

  
  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  devise_for :users,skip: [:passwords], controllers:{
     registrations: "public/registrations",
     sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'users/guset_sgin_in' => "public/sessions#guest_sign_in"
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get 'homes/top'
    resources :spot_genres, only:[:index, :edit, :create, :update, :destroy]
    get 'users/unsubscribe' => 'users#unsubscribe'
    resources :users, only: [:index, :show,]
    get 'posts/show' => 'posts#show'
    resources :posts, only: [:destroy]
    patch 'users/withdraw' => 'users#withdraw', as: 'withdraw'
    delete 'post_comment/destroy/:post_id/:id' => 'post_comments#destroy', as: 'post_comment_destroy'
    get "search" => "searches#search"

  end

  scope module: :public do
    get 'users/user_page' => 'users#user_page', as: 'user'
    get 'users/mypage' => 'users/mypage', as: 'mypage'
    get 'users/information/edit' => 'users#edit', as: 'edit_user'
    patch 'users/information' => 'users#update', as: 'update_user'
    get 'users/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch 'users/withdraw' => 'users#withdraw', as: 'withdraw'
    get "users/:id/favorites" => "users#favorites",as: "user_favorites"
    get "search" => "searches#search"

    resources :posts, only: [:new,:index,:create,:destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    get 'posts/travel_post' => 'posts#show'


  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  before_create -> { self.id = SecureRandom.uuid }
  has_one_attached :image
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  validates :title,presence:true
  validates :post_text,presence:true,length:{maximum:200}
  validates :image, presence: true

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/sample_post.jpeg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def self.looks(word)
    if word.present?
      @post = Post.where("title LIKE?","%#{word}%").or(Post.where("post_text LIKE?","%#{word}%"))
    else
      @post = Post.all
    end
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  enum prefectures_genre: {
    hokkaido:0, aomori:1, iwate:2, miyagi:3, akita:4, yamagata:5, fukusima:6, ibaraki:7, tochigi:8, gunma:9, saitama:10, chiba:11, tokyo:12, kanagawa:13,
    niigata:14, toyama:15, ishikawa:16, hukui:17, yamanashi:18, nagano:19, gihu:20, shizuoka:21, aichi:22, mie:23, shiga:24, kyoto:25, osaka:26, hyogo:27, nara:28, wakayama:29,
    tottori:30, shimane:31, okayama:32, hiroshima:33, yamaguchi:34, tokushima:35, kagawa:36, ehime:37, kochi:38, fukuoka:39, saga:40, nagasaki:41, kumamoto:42,
    oita:43, miyazaki:44, kagoshima:45, okinawa:46
    }
end

app/controllers/admin/post_controller.rb
class Admin::PostController < ApplicationController
  def show
    @post = Post.find(params[:id])
    @spot_genres = SpotGenre.all
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_homes_top_path
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @spot_genres = SpotGenre.all
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_homes_top_path, notice: '投稿の削除に成功しました。'
  end
end

app/helpers/admin/post_helper.rb
module Admin::PostHelper
end

app/views/admin/posts/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3 mt-4'>
      <%= render 'layouts/genre', spot_genres: @spot_genres %>
    </div>
    <div class='col-md-7 offset-md-1'>
      <div class='row py-md-3 pl-md-4'>
        <h2>
          <%= link_to @post.user.name, admin_user_path(@post.user.id) %>さんの旅の詳細
        </h2>
      </div>
      <div class="card">
        <div class="card-header">
          <div class="title">
            <h4><%= @post.title %></h4>
          </div>
          <div class="date text-right">
            <small><%= @post.created_at.strftime('%Y年%m月%d日') %></small>
          </div>
        </div>

        <%= image_tag @post.get_image(500,500), class: 'img-fluid' %>

        <div class="card-body">
          <%= simple_format(@post.post_text) %>
        </div>

        <div class="card-footer">
          <div class="row">
            <div class="col-md-12 text-right">
                <%= link_to "投稿を削除", admin_post_path(@post), method: :delete, data: { confirm: '本当に投稿を削除しますか？' }, class: "btn btn-sm btn-danger"%>
            </div>
          </div>
        </div>
      </div>
      <div class="mt-3">
        <%= link_to "戻る", :back, class: 'btn btn-success' %>
      </div>

      <h5 class="mt-5">コメント一覧</h5>
      <div class="mb-3">
        <small class="text-black-50">コメント件数:<%= @post.post_comments.count %></small>
      </div>

      <% @post.post_comments.each do |post_comment| %>
        <div class="card mb-3">
          <div class="card-header">
            <div class="row">
              <div class="col-md-6">
                <%= image_tag post_comment.user.get_image(50,50), class: 'd-block mb-2' %>
                <%= post_comment.user.name %>
              </div>
              <div class="col-md-6 d-flex align-items-end justify-content-end">
                <small><%= post_comment.created_at.strftime('%Y/%m/%d') %></small>
              </div>
            </div>
          </div>
          <div class="card-body">
            <%= simple_format(post_comment.post_comment) %>
          </div>
          <div class="card-footer text-right">
            <%= link_to "コメントを削除", admin_post_comment_destroy_path(post_comment.post, post_comment), method: :delete, data: { confirm: '本当にコメントを削除しますか？' }, class: "btn btn-sm btn-danger" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>