config/routes.rb
Rails.application.routes.draw do

  
  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  devise_for :users,skip: [:passwords], controllers:{
     registrations: "public/registrations",
     sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'users/guset_sgin_in' => "public/sessions#guest_sign_in"
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get 'homes/top'
    resources :spot_genres, only:[:index, :edit, :create, :update, :destroy]
    get 'users/unsubscribe' => 'users#unsubscribe'
    resources :users, only: [:index, :show,]
    get 'posts/show' => 'posts#show'
    resources :posts, only: [:destroy]
    patch 'users/withdraw' => 'users#withdraw', as: 'withdraw'
    delete 'post_comment/destroy/:post_id/:id' => 'post_comments#destroy', as: 'post_comment_destroy'
    get "search" => "searches#search"

  end

  scope module: :public do
    get 'users/user_page' => 'users#user_page', as: 'user'
    get 'users/mypage' => 'users/mypage', as: 'mypage'
    get 'users/information/edit' => 'users#edit', as: 'edit_user'
    patch 'users/information' => 'users#update', as: 'update_user'
    get 'users/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch 'users/withdraw' => 'users#withdraw', as: 'withdraw'
    get "users/:id/favorites" => "users#favorites",as: "user_favorites"
    get "search" => "searches#search"

    resources :posts, only: [:new,:index,:create,:destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    get 'posts/travel_post' => 'posts#show'


  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @posts = Post.includes(:user).where(users: {is_deleted: false}).page(params[:page]).order(created_at: :desc)
    @spot_genres = SpotGenre.all
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/about.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-12'>
      <h1 class='row pt-md-4 justify-content-center'><strong>Hey-Travelとは</strong></h1>
      <h3 class='row pt-md-4 text-center justify-content-center border-bottom'>
        <p>
          Hey-Travelでは旅行の記録を投稿したり、投稿を探して旅行のプラン作成の参考に<br>
          したりするコミュニティサイトです。会員登録をしても必ずしも投稿する<br>
          必要はございません。他ユーザーの投稿を観覧し情報収集するだけなど、<br>
          ご自身に合う使い方で自由にHey-Travelをお楽しみください。
        </p>
      </h3>
      <h3 class='row pt-md-5 justify-content-center'>新規会員登録は<%= link_to "こちら", new_user_registration_path %>から</h3>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<main>
  <div class='container'>
    <div class="text-center pt-md-3"><h5><strong><%= flash[:notice] %></strong></h5></div>
    <div class='row'>
      <div class='col-md-12'>
        <h1 class='text-center my-md-4'>
          Hey-Travelへようこそ<br>
          新規登録をして旅行を始めよう<br>
        </h1>
        <h2 class='text-center mt-md-3'>
          登録を迷っている方は是非<%= link_to "こちら", home_about_path %>でHey-Travelがどんなサイトなのか<br>
          ご覧ください！
        </h2>
        <div class="text-center">
          <%= image_tag 'top_image2.jpg', size: '700x400' %>
        </div>
        <div class='btn-wrapper col-md-3 mx-auto'>
          <div class='row'>
            <%= link_to "ゲストログイン（閲覧用）", users_guset_sgin_in_path, class: "btn btn-secondary btn-lg btn-block sign_in", method: :post %>
          </div>
          <div class='row my-md-3'>
            <%= link_to "新規登録", new_user_registration_path,class: "btn btn-success btn-lg btn-block sign_up" %>
          </div>
          <div class='row'>
            <%= link_to "ログイン", new_user_session_path,class: "btn btn-info btn-lg btn-block sign_in" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>