config/routes.rb
Rails.application.routes.draw do

  
  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  devise_for :users,skip: [:passwords], controllers:{
     registrations: "public/registrations",
     sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'users/guset_sgin_in' => "public/sessions#guest_sign_in"
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get 'homes/top'
    resources :spot_genres, only:[:index, :edit, :create, :update, :destroy]
    get 'users/unsubscribe' => 'users#unsubscribe'
    resources :users, only: [:index, :show,]
    get 'posts/show' => 'posts#show'
    resources :posts, only: [:destroy]
    patch 'users/withdraw' => 'users#withdraw', as: 'withdraw'
    delete 'post_comment/destroy/:post_id/:id' => 'post_comments#destroy', as: 'post_comment_destroy'
    get "search" => "searches#search"

  end

  scope module: :public do
    get 'users/user_page' => 'users#user_page', as: 'user'
    get 'users/mypage' => 'users/mypage', as: 'mypage'
    get 'users/information/edit' => 'users#edit', as: 'edit_user'
    patch 'users/information' => 'users#update', as: 'update_user'
    get 'users/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch 'users/withdraw' => 'users#withdraw', as: 'withdraw'
    get "users/:id/favorites" => "users#favorites",as: "user_favorites"
    get "search" => "searches#search"

    resources :posts, only: [:new,:index,:create,:destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    get 'posts/travel_post' => 'posts#show'


  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :post

end

app/models/post.rb
class Post < ApplicationRecord
  before_create -> { self.id = SecureRandom.uuid }
  has_one_attached :image
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  validates :title,presence:true
  validates :post_text,presence:true,length:{maximum:200}
  validates :image, presence: true

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/sample_post.jpeg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def self.looks(word)
    if word.present?
      @post = Post.where("title LIKE?","%#{word}%").or(Post.where("post_text LIKE?","%#{word}%"))
    else
      @post = Post.all
    end
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  enum prefectures_genre: {
    hokkaido:0, aomori:1, iwate:2, miyagi:3, akita:4, yamagata:5, fukusima:6, ibaraki:7, tochigi:8, gunma:9, saitama:10, chiba:11, tokyo:12, kanagawa:13,
    niigata:14, toyama:15, ishikawa:16, hukui:17, yamanashi:18, nagano:19, gihu:20, shizuoka:21, aichi:22, mie:23, shiga:24, kyoto:25, osaka:26, hyogo:27, nara:28, wakayama:29,
    tottori:30, shimane:31, okayama:32, hiroshima:33, yamaguchi:34, tokushima:35, kagawa:36, ehime:37, kochi:38, fukuoka:39, saga:40, nagasaki:41, kumamoto:42,
    oita:43, miyazaki:44, kagoshima:45, okinawa:46
    }
end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :post

end

app/models/spot_genre.rb
class SpotGenre < ApplicationRecord

  has_many :posts

end

app/models/user.rb
class User < ApplicationRecord
  before_create -> { self.id = SecureRandom.uuid }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  validates :name, length: { minimum: 2, maximum: 20 }


  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @posts = Post.includes(:user).where(users: {is_deleted: false}).page(params[:page]).order(created_at: :desc)
    @spot_genres = SpotGenre.all
  end
end

app/controllers/admin/post_controller.rb
class Admin::PostController < ApplicationController
  def show
    @post = Post.find(params[:id])
    @spot_genres = SpotGenre.all
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_homes_top_path
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @spot_genres = SpotGenre.all
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_homes_top_path, notice: '投稿の削除に成功しました。'
  end
end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController
  def search
    @range = params[:range]
    @users = User.where("name LIKE?","%#{params[:word]}%").page(params[:page])
    render 'admin/users/index'
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).order(created_at: :desc)
    @spot_genres = SpotGenre.all
  end

  def index
    @users = User.page(params[:page]).order(created_at: :desc)
  end

  def unsubscribe
    @user = User.find(params[:id])
  end

  def withdraw
    @user = User.find(params[:id])
    @user.update(is_deleted: true)
    redirect_to admin_users_path, notice: "退会処理が完了しました。"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

  def ensure_guest_user
    if current_user.name == "guestuser"
      flash[:notice] = 'ゲストユーザーでは操作できません'
      redirect_to mypage_path
    end
  end

  def authenticate_admin_or_user!
    if admin_signed_in? || user_signed_in?
    else 
      redirect_to root_path
    end
  end
  

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/post_comment_helper.rb
module Admin::PostCommentHelper
end

app/helpers/admin/post_helper.rb
module Admin::PostHelper
end

app/helpers/admin/search_helper.rb
module Admin::SearchHelper
end

app/helpers/admin/spot_genres_helper.rb
module Admin::SpotGenresHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/users/index.html.erb
<div class='container'>
  <div class="text-center pt-md-3"><h5><strong><%= flash[:notice] %></strong></h5></div>
  <div class='row'>
    <div class='col-md-12'>
      <h2 class='mt-md-4'>会員の登録情報</h2>
      <div class="d-flex justify-content-end pb-md-3">
        <%= render 'admin/searches/search' %>
      </div>
      <table class='table'>
        <thead>
          <tr>
            <td>会員ID</td>
            <td>名前</td>
            <td>ステータス</td>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <th><%= user.id %></td>
              <td><%= link_to user.name, admin_user_path(user.id) %></td>
              <td>
                <% if user.is_deleted == false %>
                  <p>有効</p>
                <% elsif %>
                  <p class="text-danger">退会</p>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @users %>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3 affset-md-1 d-flex align-items-center'>
      <%= render 'layouts/genre', spot_genres: @spot_genres %>
    </div>
    <div class='col-md-8'>
      <div class='row'>
        <table class='table'>
          <thead>
            <tr>
              <th style="height: 140px; border: none;"><%= image_tag @user.get_image(100,100) %></th>
            </tr>
            <tr>
              <td>名前</td>
              <td><%= @user.name %></td>
            </tr>
            <tr style="border-bottom: 1px solid #dee2e6">
              <td>自己紹介文</td>
              <td><%= @user.introduction %></td>
            </tr>
            <tr>
              <th style="border: none"><%= link_to "退会処理", admin_users_unsubscribe_path(id: @user.id),class: "btn btn-danger" %></th>
            </tr>
          </thead>
        </table>
      </div>
      <div class='row'>
        <h2>旅の記録</h2>
        <table class='table'>
          <thead>
            <tr>
              <th>日付</th>
              <th>タイトル</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @posts.each do |post| %>
              <tr>
                <td><%= post.created_at.strftime('%Y年%m月%d日') %></td>
                <td>
                  <%= link_to admin_posts_show_path(id: post.id) do %>
                    <%= post.title %>
                  <% end %>
                </td>
                <td>コメント数:<%= post.post_comments.count %> </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <%= paginate @posts %>
      <div class="mt-3">
        <%= link_to "戻る", :back, class: 'btn btn-success' %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/unsubscribe.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-md-12">
      <div class='row justify-content-center pt-md-5'>
        <h2><strong>本当に退会をさせますか？</strong></h2><br>
      </div>
      <div class='row justify-content-center pt-md-3'>
        <h4>退会処理を行うとこのアカウントは再利用できなくなります。</h4>
      </div>
      <div class='row justify-content-center pt-md-3'>
        <div class='form-group'>
          <%= form_with  url: admin_withdraw_path, method: :patch, local: true do |f| %>
            <%= f.hidden_field :id, value: @user.id %>
            <%= f.submit "退会", class: "btn btn-primary" %>
          <% end %>
        </div>
        <div class='form-group pl-md-3'>
          <%= link_to "退会しない", admin_user_path(@user.id),class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  </div>
</div>