config/routes.rb
Rails.application.routes.draw do

  
  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  devise_for :users,skip: [:passwords], controllers:{
     registrations: "public/registrations",
     sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'users/guset_sgin_in' => "public/sessions#guest_sign_in"
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get 'homes/top'
    resources :spot_genres, only:[:index, :edit, :create, :update, :destroy]
    get 'users/unsubscribe' => 'users#unsubscribe'
    resources :users, only: [:index, :show,]
    get 'posts/show' => 'posts#show'
    resources :posts, only: [:destroy]
    patch 'users/withdraw' => 'users#withdraw', as: 'withdraw'
    delete 'post_comment/destroy/:post_id/:id' => 'post_comments#destroy', as: 'post_comment_destroy'
    get "search" => "searches#search"

  end

  scope module: :public do
    get 'users/user_page' => 'users#user_page', as: 'user'
    get 'users/mypage' => 'users/mypage', as: 'mypage'
    get 'users/information/edit' => 'users#edit', as: 'edit_user'
    patch 'users/information' => 'users#update', as: 'update_user'
    get 'users/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch 'users/withdraw' => 'users#withdraw', as: 'withdraw'
    get "users/:id/favorites" => "users#favorites",as: "user_favorites"
    get "search" => "searches#search"

    resources :posts, only: [:new,:index,:create,:destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    get 'posts/travel_post' => 'posts#show'


  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :post

end

app/models/post.rb
class Post < ApplicationRecord
  before_create -> { self.id = SecureRandom.uuid }
  has_one_attached :image
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  validates :title,presence:true
  validates :post_text,presence:true,length:{maximum:200}
  validates :image, presence: true

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/sample_post.jpeg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def self.looks(word)
    if word.present?
      @post = Post.where("title LIKE?","%#{word}%").or(Post.where("post_text LIKE?","%#{word}%"))
    else
      @post = Post.all
    end
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  enum prefectures_genre: {
    hokkaido:0, aomori:1, iwate:2, miyagi:3, akita:4, yamagata:5, fukusima:6, ibaraki:7, tochigi:8, gunma:9, saitama:10, chiba:11, tokyo:12, kanagawa:13,
    niigata:14, toyama:15, ishikawa:16, hukui:17, yamanashi:18, nagano:19, gihu:20, shizuoka:21, aichi:22, mie:23, shiga:24, kyoto:25, osaka:26, hyogo:27, nara:28, wakayama:29,
    tottori:30, shimane:31, okayama:32, hiroshima:33, yamaguchi:34, tokushima:35, kagawa:36, ehime:37, kochi:38, fukuoka:39, saga:40, nagasaki:41, kumamoto:42,
    oita:43, miyazaki:44, kagoshima:45, okinawa:46
    }
end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :post

end

app/models/spot_genre.rb
class SpotGenre < ApplicationRecord

  has_many :posts

end

app/models/user.rb
class User < ApplicationRecord
  before_create -> { self.id = SecureRandom.uuid }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  validates :name, length: { minimum: 2, maximum: 20 }


  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @posts = Post.includes(:user).where(users: {is_deleted: false}).page(params[:page]).order(created_at: :desc)
    @spot_genres = SpotGenre.all
  end
end

app/controllers/admin/post_controller.rb
class Admin::PostController < ApplicationController
  def show
    @post = Post.find(params[:id])
    @spot_genres = SpotGenre.all
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_homes_top_path
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @spot_genres = SpotGenre.all
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_homes_top_path, notice: '投稿の削除に成功しました。'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

  def ensure_guest_user
    if current_user.name == "guestuser"
      flash[:notice] = 'ゲストユーザーでは操作できません'
      redirect_to mypage_path
    end
  end

  def authenticate_admin_or_user!
    if admin_signed_in? || user_signed_in?
    else 
      redirect_to root_path
    end
  end
  

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/post_comment_helper.rb
module Admin::PostCommentHelper
end

app/helpers/admin/post_helper.rb
module Admin::PostHelper
end

app/helpers/admin/search_helper.rb
module Admin::SearchHelper
end

app/helpers/admin/spot_genres_helper.rb
module Admin::SpotGenresHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <nav class="navbar navbar-expand-lg navbar-dark bg-info mt-md-4">
    <div class='container mt-5'>
  	  <div class='row'>
      	<div class='mx-auto'>
      	</div>
      </div>
    </div>
  </nav>
</footer>

app/views/layouts/_genre.html.erb
<div class='card'>
  <div class='card-header text-center'>
    <h4>ジャンル検索</h4>
  </div>
  <div class='card-body'>
    <%= form_with url: posts_path, local:true, method: :get do |f| %>
        <div class='form-group'>
          <%= f.label :prefectures_genre, "都道府県" %>
          <%= f.select :prefectures_genre, Post.prefectures_genres.keys.map {|k| [I18n.t("enums.post.prefectures_genre.#{k}"), k]}, { selected: params[:prefectures_genre] } %>
        </div>
        <div class='form-group'>
          <%= f.label :spot_genre_id, "スポット" %>
          <%= f.select :spot_genre_id, SpotGenre.pluck(:spot_genre, :id), { selected: params[:spot_genre_id] } %>
        </div>
        <div class="form-group">
          <%= f.submit "検索する", class: 'btn btn-success', name: nil %>
        </div>
      <% end %>
  </div>
</div>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-info md-md-4">
    <div class="container mt-3">
      <a class="navbar-brand" href="/">
        <span>
          <%= link_to root_path do %>
            <h2 class="text-white"><i class="fas fa-plane"></i> Hey-Travel</h2>
          <% end %>
        </span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">

          <% if admin_signed_in? %>
            <li>
              <%= link_to admin_users_path, class: 'nav-link text-light' do %>
                <p>会員一覧</p>
              <% end %>
            </li>
            <li>
              <%= link_to admin_homes_top_path, class: 'nav-link text-light' do %>
                <p>投稿一覧</p>
              <% end %>
            </li>
            <li>
              <%= link_to admin_spot_genres_path, class: 'nav-link text-light' do %>
                <p>ジャンル一覧</p>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-light' do %>
                <p>ログアウト</p>
              <% end %>
            </li>
            <%= render 'public/searches/searche' %>
          <% elsif user_signed_in? %>
            <li>
              <%= link_to mypage_path, class: 'nav-link text-light' do %>
                <i class="fas fa-user"></i> マイページ
              <% end %>
            </li>
            <% if current_user.email != 'guest@example.com' %>
              <li>
                <%= link_to new_post_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-paper-plane"></i> 投稿する
                <% end %>
              </li>
            <% end %>
            <li>
              <%= link_to posts_path, class: 'nav-link text-light' do %>
                <i class="fas fa-suitcase"></i> 投稿一覧
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                <i class="fas fa-sign-out-alt"></i> ログアウト
              <% end %>
            </li>
            <%= render 'public/searches/searche' %>
          <% else %>
            <li>
              <%= link_to home_about_path, class: 'nav-link text-light' do %>
                <i class="fas fa-book-reader"></i> Hey-Travelとは
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                <i class="fas fa-user-plus"></i> 新規登録
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                 <i class="fas fa-sign-in-alt"></i> ログイン
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hey-Travel</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('favicon.ico') %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>